steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/bingit/bingit-assignment-2:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'bingit-assignment-2:base',
    '-t', 'gcr.io/bingit/bingit-assignment-2:base',
    '--cache-from', 'gcr.io/bingit/bingit-assignment-2:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bingit/bingit-assignment-2:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/bingit/bingit-assignment-2:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/bingit/bingit-assignment-2:coverage',
    '.'
  ]
images: ['gcr.io/bingit/bingit-assignment-2:base', 'gcr.io/bingit/bingit-assignment-2:latest', 'gcr.io/bingit/bingit-assignment-2:coverage']
